import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

interface LogSessionRequest {
    sessionId: string;
    summary: string;
    problems?: string;
    solutions?: string;
    status?: string;
    nextSteps?: string;
    confidence?: string;
    recommendations?: string;
    content: string; // Full chat transcript
}

export async function POST(req: NextRequest) {
    try {
        const body: LogSessionRequest = await req.json();
        const {
            sessionId,
            summary,
            problems = 'None documented',
            solutions = 'N/A',
            status = 'In Progress',
            nextSteps = 'Continue development',
            confidence = 'N/A',
            recommendations = 'None',
            content
        } = body;

        // Get project root (go up from app/ to project root)
        const projectRoot = path.join(process.cwd(), '..', '..');
        const reportDir = path.join(projectRoot, 'Session_Reports');

        // Create report directory if it doesn't exist
        if (!fs.existsSync(reportDir)) {
            fs.mkdirSync(reportDir, { recursive: true });
        }

        // Get current date and month folder
        const today = new Date();
        const dateStr = today.toISOString().split('T')[0]; // YYYY-MM-DD
        const monthFolder = today.toLocaleString('en-US', { month: 'long', year: 'numeric' }); // "January 2026"
        const monthDir = path.join(reportDir, monthFolder);

        // Create month directory if it doesn't exist
        if (!fs.existsSync(monthDir)) {
            fs.mkdirSync(monthDir, { recursive: true });
        }

        // Find next session number for today
        const pattern = path.join(monthDir, `${dateStr}_Session*.md`);
        const existingFiles = fs.readdirSync(monthDir).filter(f => 
            f.startsWith(`${dateStr}_Session`) && f.endsWith('.md')
        );

        let sessionNum = 1;
        if (existingFiles.length > 0) {
            const sessionNumbers = existingFiles.map(f => {
                const match = f.match(/_Session(\d+)\.md$/);
                return match ? parseInt(match[1]) : 0;
            });
            sessionNum = Math.max(...sessionNumbers) + 1;
        }

        const filename = `${dateStr}_Session${sessionNum}.md`;
        const fullPath = path.join(monthDir, filename);

        // Format date for display
        const displayDate = today.toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });

        // Generate report content using template
        const reportContent = `# SESSION REPORT: Session ${sessionNum}
**Date:** ${displayDate}
**Session ID:** ${sessionId}

---

## 🧭 Executive Summary
> ${summary}

---

## 🛠️ Technical Deep Dive
### Problems Encountered
${problems}

### Solutions & Key Decisions
${solutions}
--- 

## 📊 Project Health
> **Confidence Score:** ${confidence}

## 💡 AI Recommendations
${recommendations}

---

## 📍 Current Project State
* **Development Phase:** ${status}
* **Session ID:** ${sessionId}

---

## 🔮 Next Steps & Action Items
${nextSteps}

---

## 📝 Transcript & Context (Raw Log)
<details>
<summary>Click to expand full chat history</summary>

${content}

</details>

---

*Generated by 5D Character Creator • Session Auto-Logger*
`;

        // Write file
        fs.writeFileSync(fullPath, reportContent, 'utf-8');

        return NextResponse.json({
            success: true,
            path: fullPath,
            filename,
            monthFolder,
            sessionNum
        });

    } catch (error) {
        console.error('Failed to log session:', error);
        return NextResponse.json(
            { 
                error: 'Failed to log session',
                details: error instanceof Error ? error.message : String(error)
            },
            { status: 500 }
        );
    }
}
